---
variables: &global_variables
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: tcp://docker:2375
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  FPM_IMAGE_TAG: $CI_REGISTRY_IMAGE:${CI_COMMIT_REF_NAME}-fpm
  PACKAGE_NAME: ursula
  PACKAGE_URL: https://git.vshn.net/appuio-public/ursula/
  PACKAGE_DESC: Cloud provider API integration for Keepalived

stages:
  - build
  - packages

.docker_job: &docker_job
  tags:
    - dockerbuild
  image:
    name: docker.io/library/docker:stable
  services:
    - name: docker:stable-dind
  before_script:
    - docker login --username gitlab-ci-token --password "$CI_JOB_TOKEN" "$CI_REGISTRY"
  after_script:
    - docker logout "$CI_REGISTRY"

build:
  stage: build
  <<: *docker_job
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    expire_in: 1 day
    paths:
      - _artifacts/package.tar
  script:
    - |-
      docker build \
        --file ./Dockerfile \
        --tag "$IMAGE_TAG" \
        --build-arg "CI_COMMIT_REF_NAME=$CI_COMMIT_REF_NAME" \
        --build-arg "CI_COMMIT_SHA=$CI_COMMIT_SHA" \
        .

    # Extract files to be packaged into archive (tar runs in container)
    - test -d _artifacts || mkdir -v _artifacts
    - |-
      docker run --rm --entrypoint /bin/tar "$IMAGE_TAG" -C / -cf - \
        bin/ursula \
        > _artifacts/package.tar

    - docker push "$IMAGE_TAG"

build-fpm:
  stage: build
  <<: *docker_job
  script:
    - |-
      docker build \
        --file ./Dockerfile.fpm \
        --tag "$FPM_IMAGE_TAG" \
        .
    - docker push "$FPM_IMAGE_TAG"

packages:
  stage: packages
  image:
    name: "$FPM_IMAGE_TAG"
    entrypoint: [""]
  variables:
    <<: *global_variables
    GIT_STRATEGY: none
  services: []
  dependencies:
    - build
  artifacts:
    name: $CI_COMMIT_REF_SLUG
    expire_in: 1 week
    paths:
      - _artifacts/*.deb
      - _artifacts/*.rpm
  script:
    - |-
      build_package() { \
        (
          cd _artifacts && \
          exec fakeroot fpm --verbose \
          --input-type tar \
          --prefix /usr \
          --name "$PACKAGE_NAME" \
          --description "$PACKAGE_DESC" \
          --url "$PACKAGE_URL" \
          "$@" \
          -- \
          package.tar;
        ); \
      }

    - |-
      ref_name="$CI_COMMIT_REF_NAME" &&
      if [[ "$ref_name" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
        # Version tag, strip first character
        pkgver="${ref_name:1}"
      else
        ref_name="$CI_COMMIT_REF_SLUG" &&
        pkgver="devel.${ref_name:-unknown}"
      fi

    - today="$(date +%Y%m%d)"

    # Make truncated commit ID
    - commit_sha="$CI_COMMIT_SHA"
    - commit_sha="${commit_sha:0:8}"

    # https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-version
    - deb_version="${pkgver}.${today}${commit_sha:+~git${commit_sha}}"
    - build_package --output-type deb --version "$deb_version"

    # https://fedoraproject.org/wiki/Packaging:Versioning
    - rpm_version="${pkgver}.${today}${commit_sha:+git${commit_sha}}"
    - build_package --output-type rpm --version "$rpm_version"

# vim: set sw=2 sts=2 et :
