# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

builds:
  - env:
      - CGO_ENABLED=0 # this is needed otherwise the Docker image build is faulty
    goarch:
      - amd64
    goos:
      - linux

archives:
  - format: binary
    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-snapshot"

signs:
  - artifacts: checksum
    args: ["-u", "49B2C495F81DD5AD15CA24B2B56474B9CF8D7FAC", "--output", "${signature}", "--detach-sign", "${artifact}"]

dockers:
  - image_templates:
      - "quay.io/vshn/floaty:v{{ .Version }}"

      # For prereleases, updating `latest` and the floating tags of the major version does not make sense.
      # Only the image for the exact version should be pushed.
      - "{{ if not .Prerelease }}quay.io/vshn/floaty:v{{ .Major }}{{ end }}"
      - "{{ if not .Prerelease }}quay.io/vshn/floaty:latest{{ end }}"

nfpms:
  - vendor: VSHN
    homepage: https://github.com/vshn/floaty
    maintainer: VSHN AG
    description: Floaty. Cloud provider API integration for Keepalived.
    license: BSD 3-Clause
    file_name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    formats:
      - deb
      - rpm
      - apk

release:
  prerelease: auto
  github:
    owner: vshn
    name: floaty
